-- liquibase formatted sql

-- changeset BFGprog:1
create table if not exists recommendations (
  id bigint generated by default as identity primary key,
	product_name CHARACTER VARYING(255) NOT NULL,
	product_id UUID NOT NULL,
  product_text text NOT NULL
);
create table if not exists rules (
    recommendation_id bigint NOT NULL,
	query CHARACTER VARYING(255) NOT NULL,
	arguments CHARACTER VARYING(255) NOT NULL,
	negate BOOL NOT NULL,
	FOREIGN KEY (recommendation_id) REFERENCES recommendations(id)
);





