-- liquibase formatted sql

-- changeset BFGprog:1
create table if not exists public.recommendations (
  id BIGINT generated by default as identity primary key,
	product_name CHARACTER VARYING(255) NOT NULL,
	product_id UUID NOT NULL,
  product_text text NOT NULL
);
create table if not exists public.rules (
    rules_id BIGINT generated by default as identity primary key,
	query CHARACTER VARYING(255) NOT NULL,
	arguments CHARACTER VARYING(255) NOT NULL,
	negate BOOL NOT NULL,
	recommendation_id BIGINT NULL,
	FOREIGN KEY (recommendation_id) REFERENCES recommendations(id)
	on delete cascade
);

-- changeset BFGprog:2
ALTER TABLE public.rules
ADD count int NOT NULL DEFAULT 0;






